spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/{이름}?useSSL=false&allowPublicKeyRetrieval=true
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true