spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: smc0416!@

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true